export const LAYOUT_CONSTANTS = {
  TASKBAR_HEIGHT: 44,
  
  DESKTOP_CELL_SIZE: 80,
  
  WINDOW_MIN_WIDTH: 200,
  WINDOW_MIN_HEIGHT: 150,
  
  WINDOW_STACK_OFFSET: 30,
  WINDOW_STACK_CYCLE_COUNT: 5,
  
  MOBILE_BREAKPOINT: 500,
  TABLET_BREAKPOINT: 1024,
  
  MOBILE_MARGIN: 20,
  MOBILE_MIN_MARGIN: 5,
  TABLET_MARGIN: 40,
  TABLET_MIN_MARGIN: 20,
  DESKTOP_MARGIN: 40,
  DESKTOP_MIN_MARGIN: 20,
  
  DEFAULT_WINDOW: {
    WIDTH: 384,
    HEIGHT: 320
  },
  
  MOBILE_WINDOW: {
    MAX_WIDTH: 350,
    MAX_HEIGHT: 400
  },
  
  Z_INDEX: {
    BASE: 1000,
    START_MENU: 2000,
    TASKBAR: 1500
  }
} as const;